service:
  name: crudapp
  version: 0.1.0
  environment: dev
  addr: localhost:8080

logFormat: console

trace:
  enabled: false
  providerURL: localhost:4317

storage:
  type: memory

  mongodb:
    url: mongodb://mongodb:password@127.0.0.1:27017

  postgres:
    url: postgres://postgres:password@127.0.0.1:5432/postgres

cache:
  type: noop
  size: 10000

  memcached:
    servers: localhost:11211

  redis:
    addr: localhost:6379
    password:
