version: "3"
services:
  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
    
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=password

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-local-config.yaml"]
    ports:
      - "1888:1888"    # pprof extension
      - "8888:8888"    # Prometheus metrics exposed by the collector
      - "8889:8889"    # Prometheus exporter metrics
      - "13133:13133"  # health_check extension
      - "55679:55679"  # zpages extension
      - "4317:4317"
    volumes:
      - "${PWD}/telemetry/otel-config.yaml:/etc/otel-local-config.yaml"
    depends_on:
      - zipkin
      - jaeger
  
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"
